version: '2'
services:
    # The Application
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./findyourway:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
        links:
            - database
        depends_on:
            - database
        networks:
            - internal-net

    # The Web Server
    web:
        image: nginx:1.10
        working_dir: /var/www
        volumes:
            - ./confs/vhost.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - app
        ports:
            - 8080:80
        networks:
            - internal-net

    # The Database
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_DATABASE=findyourway"
            - "MYSQL_USER=findyourway"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
                - "33061:3306"
        networks:
            - internal-net

    # The Administration Panel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - database
        environment:
            PMA_PORT: 3306
            PMA_HOST: database
            PMA_USER: findyourway
            PMA_PASSWORD: secret
        ports:
            - "8181:80"
        restart: always
        depends_on: 
            - database
        networks:
            - internal-net

networks:
  internal-net:
    driver: bridge
